from GenBase import *
# define sample values
A=GenBase()
A.b1 = 10
A.x1 = 3

A.b2 = 8
A.x2 = 255

A.x3 = 3421
A.b3 = 16

A.x = GenBase(A.b1, A.x1)
A.y = GenBase(A.b2, A.x2)
A.z = GenBase(A.b3, A.x3)

print(' A.x1 + A.x2')
print(A.x + A.y, GenBase(A.b1, A.x1 + A.x2))
print(' A.x2 + A.x1')
print(A.y + A.x, GenBase(A.b2, A.x2 + A.x1))
print(' A.x3 + A.x2')
print(A.z + A.y, GenBase(A.b3, A.x3 + A.x2))
print(' A.x2 + A.x3')
print(A.y + A.z, GenBase(A.b2, A.x2 + A.x3))
print(' A.x1 - A.x2')
print(A.x - A.y, GenBase(A.b1, A.x1 - A.x2))
print(' A.x2 - A.x1')
print(A.y - A.x, GenBase(A.b2, A.x2 - A.x1))
print(' A.x3 - A.x2')
print(A.z - A.y, GenBase(A.b3, A.x3 - A.x2))
print(' A.x2 - A.x3')
print(A.y - A.z, GenBase(A.b2, A.x2 - A.x3))
print(' A.x1 * A.x2')
print(A.x * A.y, GenBase(A.b1, A.x1 * A.x2))
print(' A.x2 * A.x1')
print(A.y * A.x, GenBase(A.b2, A.x2 * A.x1))
print(' A.x3 * A.x2')
print(A.z * A.y, GenBase(A.b3, A.x3 * A.x2))
print(' A.x2 * A.x3')
print(A.y * A.z, GenBase(A.b2, A.x2 * A.x3))
print(' A.x1 // A.x2')
print(A.x // A.y, GenBase(A.b1, A.x1 // A.x2))
print(' A.x2 // A.x1')
print(A.y // A.x, GenBase(A.b2, A.x2 // A.x1))
print(' A.x3 // A.x2')
print(A.z // A.y, GenBase(A.b3, A.x3 // A.x2))
print(' A.x2 // A.x3')
print(A.y // A.z, GenBase(A.b2, A.x2 // A.x3))
print(' A.x1 % A.x2')
print(A.x % A.y, GenBase(A.b1, A.x1 % A.x2))
print(' A.x2 % A.x1')
print(A.y % A.x, GenBase(A.b2, A.x2 % A.x1))
print(' A.x3 % A.x2')
print(A.z % A.y, GenBase(A.b3, A.x3 % A.x2))
print(' A.x2 % A.x3')
print(A.y % A.z, GenBase(A.b2, A.x2 % A.x3))

# print((A.x))
# print(GenBase(A.b1,A.x + A.y))
# print((A.y + A.x))
# print(GenBase(A.b2, A.y + A.x))
# print((A.x * A.y))
# print(GenBase(A.b1, A.x * A.y))
# print((A.x - A.y))
# print(GenBase(A.b1, A.x - A.y))
# print((A.x % A.y))
# print(GenBase(A.b1, A.x % A.y))
# print((A.x // A.y))
# print(GenBase(A.b1,A.x // A.y))
# print(type(A.x + A.y))
# print(type(GenBase(A.b1,A.x + A.y)))
# print(type(A.x * A.y))
# print(type(GenBase(A.b1, A.x * A.y)))
# print(type(A.x - A.y))
# print(type(GenBase(A.b1, A.x - A.y)))
# print(type(A.x % A.y))
# print(type(GenBase(A.b1, A.x % A.y)))
# print(type(A.x // A.y))
# print(type(GenBase(A.b1,A.x // A.y)))